import '@ant-design/v5-patch-for-react-19';
import "./globals.css";
import { AntdRegistry } from '@ant-design/nextjs-registry';

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className="max-w-[512px] mx-auto shadow-lg bg-white h-screen"
      >
        <AntdRegistry>{children}</AntdRegistry>
      </body>
    </html>
  );
}
